// Base de données des projets avec informations complètes
const projectsData = [
    // Département 75 - Paris
    {
        id: 1,
        name: "Jardin Partagé du Centre",
        type: "environnement",
        eventType: "environnement",
        department: "75",
        departmentName: "Paris",
        caisse: "CA Paris Île-de-France",
        caisseId: "ca-paris-idf",
        ville: "Paris 15e",
        budget: 15000,
        impact: "+200kg de légumes/an",
        icon: "leaf",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=500&q=60",
        date: "2023-06-15"
    },
    {
        id: 2,
        name: "Tournoi de Football de Quartier",
        type: "sportif",
        eventType: "sportif",
        department: "75",
        departmentName: "Paris",
        caisse: "CA Paris Île-de-France",
        caisseId: "ca-paris-idf",
        ville: "Paris 18e",
        budget: 8000,
        impact: "150 participants",
        icon: "futbol",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1459865264687-595d652de67e?auto=format&fit=crop&w=500&q=60",
        date: "2024-01-20"
    },
    {
        id: 3,
        name: "Café Associatif Le Lien",
        type: "social",
        eventType: "social",
        department: "75",
        departmentName: "Paris",
        caisse: "CA Paris Île-de-France",
        caisseId: "ca-paris-idf",
        ville: "Paris 11e",
        budget: 25000,
        impact: "50 visiteurs/jour",
        icon: "users",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&w=500&q=60",
        date: "2023-11-10"
    },
    
    // Département 69 - Rhône
    {
        id: 4,
        name: "Festival des Arts de Rue",
        type: "culturel",
        eventType: "culturel",
        department: "69",
        departmentName: "Rhône",
        caisse: "CA Centre-Est",
        caisseId: "ca-centre-est",
        ville: "Lyon",
        budget: 45000,
        impact: "5000 spectateurs",
        icon: "theater-masks",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=500&q=60",
        date: "2023-07-22"
    },
    {
        id: 5,
        name: "Maraude Solidaire",
        type: "caritatif",
        eventType: "caritatif",
        department: "69",
        departmentName: "Rhône",
        caisse: "CA Centre-Est",
        caisseId: "ca-centre-est",
        ville: "Villeurbanne",
        budget: 12000,
        impact: "80 personnes aidées/mois",
        icon: "hand-holding-heart",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=500&q=60",
        date: "2023-09-05"
    },
    {
        id: 6,
        name: "Rénovation Épicerie",
        type: "commerce",
        eventType: "commerce",
        department: "69",
        departmentName: "Rhône",
        caisse: "CA Centre-Est",
        caisseId: "ca-centre-est",
        ville: "Givors",
        budget: 18000,
        impact: "Maintien commerce rural",
        icon: "store",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1556740758-90de27424782?auto=format&fit=crop&w=500&q=60",
        date: "2023-04-18"
    },
    
    // Département 33 - Gironde
    {
        id: 7,
        name: "Marathon de Bordeaux",
        type: "sportif",
        eventType: "sportif",
        department: "33",
        departmentName: "Gironde",
        caisse: "CA Aquitaine",
        caisseId: "ca-aquitaine",
        ville: "Bordeaux",
        budget: 35000,
        impact: "3000 coureurs",
        icon: "running",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=500&q=60",
        date: "2023-10-14"
    },
    {
        id: 8,
        name: "Banque Alimentaire",
        type: "caritatif",
        eventType: "caritatif",
        department: "33",
        departmentName: "Gironde",
        caisse: "CA Aquitaine",
        caisseId: "ca-aquitaine",
        ville: "Mérignac",
        budget: 22000,
        impact: "200 familles/semaine",
        icon: "utensils",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=500&q=60",
        date: "2024-02-01"
    },
    {
        id: 9,
        name: "Exposition Patrimoine Local",
        type: "culturel",
        eventType: "culturel",
        department: "33",
        departmentName: "Gironde",
        caisse: "CA Bordeaux et Vignobles",
        caisseId: "ca-bordeaux-vignobles",
        ville: "Saint-Émilion",
        budget: 16000,
        impact: "1500 visiteurs",
        icon: "landmark",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?auto=format&fit=crop&w=500&q=60",
        date: "2023-08-30"
    },
    
    // Département 06 - Alpes-Maritimes
    {
        id: 10,
        name: "Nettoyage des Plages",
        type: "environnement",
        eventType: "environnement",
        department: "06",
        departmentName: "Alpes-Maritimes",
        caisse: "CA Provence Côte d'Azur",
        caisseId: "ca-paca",
        ville: "Nice",
        budget: 9000,
        impact: "500kg de déchets collectés",
        icon: "water",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?auto=format&fit=crop&w=500&q=60",
        date: "2023-05-20"
    },
    {
        id: 11,
        name: "Bibliothèque Nomade",
        type: "culturel",
        eventType: "culturel",
        department: "06",
        departmentName: "Alpes-Maritimes",
        caisse: "CA Provence Côte d'Azur",
        caisseId: "ca-paca",
        ville: "Cannes",
        budget: 14000,
        impact: "800 livres en circulation",
        icon: "book",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=500&q=60",
        date: "2023-12-05"
    },
    {
        id: 12,
        name: "Atelier Vélo Solidaire",
        type: "caritatif",
        eventType: "caritatif",
        department: "06",
        departmentName: "Alpes-Maritimes",
        caisse: "CA Alpes Provence",
        caisseId: "ca-alpes-provence",
        ville: "Antibes",
        budget: 11000,
        impact: "120 vélos réparés",
        icon: "bicycle",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?auto=format&fit=crop&w=500&q=60",
        date: "2024-01-08"
    },
    
    // Département 31 - Haute-Garonne
    {
        id: 13,
        name: "Parc Solaire Citoyen",
        type: "environnement",
        eventType: "environnement",
        department: "31",
        departmentName: "Haute-Garonne",
        caisse: "CA Toulouse 31",
        caisseId: "ca-toulouse-31",
        ville: "Toulouse",
        budget: 55000,
        impact: "150 foyers alimentés",
        icon: "solar-panel",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=500&q=60",
        date: "2024-02-15"
    },
    {
        id: 14,
        name: "Fête de la Musique",
        type: "culturel",
        eventType: "culturel",
        department: "31",
        departmentName: "Haute-Garonne",
        caisse: "CA Toulouse 31",
        caisseId: "ca-toulouse-31",
        ville: "Colomiers",
        budget: 28000,
        impact: "10000 participants",
        icon: "music",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=500&q=60",
        date: "2023-06-21"
    },
    {
        id: 15,
        name: "Tournoi Rugby Jeunes",
        type: "sportif",
        eventType: "sportif",
        department: "31",
        departmentName: "Haute-Garonne",
        caisse: "CA Nord Midi-Pyrénées",
        caisseId: "ca-nord-mp",
        ville: "Blagnac",
        budget: 13000,
        impact: "200 jeunes participants",
        icon: "football",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1486286701208-1d58e9338013?auto=format&fit=crop&w=500&q=60",
        date: "2023-09-28"
    },
    
    // Département 59 - Nord
    {
        id: 16,
        name: "Vestiboutique Solidaire",
        type: "caritatif",
        eventType: "caritatif",
        department: "59",
        departmentName: "Nord",
        caisse: "CA Nord de France",
        caisseId: "ca-nord-france",
        ville: "Lille",
        budget: 19000,
        impact: "300 familles aidées",
        icon: "tshirt",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=500&q=60",
        date: "2023-10-12"
    },
    {
        id: 17,
        name: "Marché Bio Hebdomadaire",
        type: "commerce",
        eventType: "commerce",
        department: "59",
        departmentName: "Nord",
        caisse: "CA Nord de France",
        caisseId: "ca-nord-france",
        ville: "Roubaix",
        budget: 21000,
        impact: "30 producteurs locaux",
        icon: "shopping-basket",
        status: "finished",
        statusLabel: "Réalisé",
        image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=500&q=60",
        date: "2023-03-10"
    },
    {
        id: 18,
        name: "Conservatoire de Musique",
        type: "culturel",
        eventType: "culturel",
        department: "59",
        departmentName: "Nord",
        caisse: "CA Brie Picardie",
        caisseId: "ca-brie-picardie",
        ville: "Tourcoing",
        budget: 38000,
        impact: "250 élèves",
        icon: "guitar",
        status: "ongoing",
        statusLabel: "En cours",
        image: "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=500&q=60",
        date: "2024-01-15"
    }
];

// Structure des caisses locales avec budget total alloué
const caissesData = {
    "75": [
        { id: "ca-paris-idf", name: "CA Paris Île-de-France", budget: 48000 }
    ],
    "69": [
        { id: "ca-centre-est", name: "CA Centre-Est", budget: 75000 },
        { id: "ca-sud-rhone-alpes", name: "CA Sud Rhône-Alpes", budget: 32000 }
    ],
    "33": [
        { id: "ca-aquitaine", name: "CA Aquitaine", budget: 57000 },
        { id: "ca-bordeaux-vignobles", name: "CA Bordeaux et Vignobles", budget: 16000 }
    ],
    "06": [
        { id: "ca-paca", name: "CA Provence Côte d'Azur", budget: 23000 },
        { id: "ca-alpes-provence", name: "CA Alpes Provence", budget: 11000 }
    ],
    "31": [
        { id: "ca-toulouse-31", name: "CA Toulouse 31", budget: 83000 },
        { id: "ca-nord-mp", name: "CA Nord Midi-Pyrénées", budget: 13000 }
    ],
    "59": [
        { id: "ca-nord-france", name: "CA Nord de France", budget: 40000 },
        { id: "ca-brie-picardie", name: "CA Brie Picardie", budget: 38000 }
    ]
};

// Départements disponibles
const departmentsData = [
    { code: "06", name: "Alpes-Maritimes" },
    { code: "31", name: "Haute-Garonne" },
    { code: "33", name: "Gironde" },
    { code: "59", name: "Nord" },
    { code: "69", name: "Rhône" },
    { code: "75", name: "Paris" }
];
